### ISSUE TITLE
COEUR DE BRIE - Innacuracy in total sales

### ISSUE THREAD

**Issue by pharmaflix** [iterait/vividi-pharmaflix#4]
GH (14/11) : We still have >10% more sales than visitors (i.e. 09/11 1327>508>496>602 ; 10/11 1568>569>558>645)

Can we improve better ?

**Comment by JulienVividi** [comment]
Hello, I've just checked and made 1 optimisation, let's see in coming days. But from what I've seen the discrepancies between the visitors and total interactions at POS could come from CAM-7 as we might catch a few people browsing the products in the right where you can see some shelves.

**Comment by pharmaflix** [comment]
can't you reduce the right POS analysis zone ? People at counter are always within 50cm from counter, POS zone as it is currently capture deeper than 1m

**Comment by JulienVividi** [comment]
Your required adjustments have been done thank you

**Comment by JulienVividi** [comment]
Adjusted results: (this pharmacy being pretty small it seems there is not much movement from the employees to disrupt the POS interactions). @pharmaflix please let me know if we can close this ticket thank you.

https://app.vividi.io/conversion/853/custom/1667775600000/1668380400000

**Comment by JulienVividi** [comment]
Hi @pharmaflix. As I didn't receive any update since 14/11 I am closing this tickets. I have check data (even from 10/11 as per your example and everything seems ok)
10/11: https://app.vividi.io/conversion/853/custom/1668034800000/1668121200000
Last month: https://app.vividi.io/conversion/853/custom/1668985200000/1671490800000

@blazekadam this issue was solved let me know if you have any objection thank you!

**Comment by pharmaflix** [comment]
Dear Julien

Thanks I didn't have time to check yet and will do in January once I'm back.

Best

Guillaume-Henri HUREL
VP Innovation Data
Pharmaflix
P//+33634381159<tel:+33634381159>
________________________________
